### Application Version ###
applicationVersion=0.0.1-SNAPSHOT

### Project configs ###
projectGroup=com.sparta
javaVersion=21

### Plugin dependency versions ###
spotlessVersion=8.8.0
palantirJavaFormatVersion=2.50.0
### Spring dependency versions ###
springBootVersion=3.5.0
springDependencyManagementVersion=1.1.7
### External depndecny versions ###
jBcrpytVersion=0.4
sentryVersion=8.12.0
querydslVersion=5.1.0
jjwtVersion=0.13.0
firebaseAdminSDKVersion=8.1.0