# ===========================================
# Spring Boot Core Settings
# ===========================================
spring:
  profiles:
    active: local

  application:
    name: sparta-tigers

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # 파일 1개당 최대 크기 (모바일 압축을 고려하여 10MB 제한)
      max-request-size: 50MB    # 5장(50MB) 제한
      file-size-threshold: 10KB # 10KB 이상의 파일은 Heap이 아닌 디스크에 임시 저장 (OOM 방어 핵심)

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

  web:
    resources:
      add-mappings: false

# ===========================================
# Spring Boot Actuator Settings (Monitoring)
# ===========================================
management:
  endpoints:
    web:
      exposure:
        include: prometheus

# ===========================================
# Logging Settings
# ===========================================
logging.config: classpath:logback/logback-${spring.profiles.active}.xml

# ===========================================
# Embedded Web Server Settings (Tomcat)
# ===========================================
server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

# ===========================================
# AWS Cloud Settings
# ===========================================
cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      folders:
        team-symbol: team-symbols/
      upload:
        max-size: 5242880
        allowed-extensions:
          - jpg
          - jpeg
          - png
    stack:
      auto: false

# ===========================================
# Firebase Settings
# ===========================================
firebase:
  project-id: "sparta-33b05"
  # 로컬: 파일 시스템, 운영: 클래스패스 리소스
  credentials-path: "firebase-key.json"

# ===============================
# Weather API
# ===============================
weather:
  api:
    key: ${WEATHER_API_KEY}
# ===============================
# OAuth Settings
# ===============================
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/oauth/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me