spring.profiles.active: local

spring:
  application:
    name: sparta-tigers

  config:
    import:
      - db.yml
      - redis.yml
      - logging.yml
      - monitoring.yml
      - jwt.yml
      - firebase.yml

  web:
    resources:
      add-mappings: false


server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100