spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

---
spring.config.activate.on-profile: local

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_LOCAL_URL}:${DATABASE_LOCAL_PORT}/${DATABASE_LOCAL_SCHEMA}
    username: ${DATABASE_LOCAL_USERNAME}
    password: ${DATABASE_LOCAL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_PROD_URL}:${DATABASE_PROD_PROT}/${DATABASE_PROD_SCHEMA}
    username: ${DATABASE_PROD_USERNAME}
    password: ${DATABASE_PROD_PASSWORD}