spring.config.activate.on-profile: local

spring:
  data:
    redis:
      host: ${redis-local-url}
      port: 6379
      timeout: 3000
      password: ${redis-local-password}

---
spring.config.activate.on-profile: prod

spring:
  data:
    redis:
      host: ${redis-prod-host}
      port: 6379
      timeout: 3000
      password: ${redis-prod-password}