spring.config.activate.on-profile: local

spring:
  data:
    redis:
      host: ${REDIS_LOCAL_URL}
      port: ${REDIS_LOCAL_PORT}
      timeout: 3000
      password: ${REDIS_LOCAL_PASSWORD}

---
spring.config.activate.on-profile: prod

spring:
  data:
    redis:
      host: ${REDIS_PROD_URL}
      port: ${REDIS_PROD_PROT}
      timeout: 3000
      password: ${REDIS_PROD_PASSWORD}