services:
  mysql:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: sparta-tigers
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - sparta-tigers

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    command: redis-server --requirepass jungmini
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - sparta-tigers

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - sparta-tigers

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/volume:/var/lib/grafana
    networks:
      - sparta-tigers

networks:
  sparta-tigers:
    driver: bridge